### ISSUE TITLE
Continually getting: RuntimeError: AT command failure: RuntimeError('Timed out waiting for a response.',)

### ISSUE THREAD

**Issue by besupernow** [adafruit/Adafruit_CircuitPython_BluefruitSPI#24]
Code : 
```python
import board
import busio
from digitalio import DigitalInOut
from adafruit_bluefruitspi import BluefruitSPI
import time
spi_bus = busio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)
cs = DigitalInOut(board.D8)
irq = DigitalInOut(board.D7)
rst = DigitalInOut(board.D6)
bluefruit = BluefruitSPI(spi_bus, cs, irq, rst, debug=True)

# Initialize the device and perform a factory reset
print("Initializing the Bluefruit LE SPI Friend module")
bluefruit.init()
bluefruit.command_check_OK(b'AT+FACTORYRESET', delay=1) #Errors here
```
The Board being used is an unexpectedmaker ProS3 with a ESP32-S3 Microchip enabled with WiFi and BLE functionality 

Output: 
```
Initializing the Bluefruit LE SPI Friend module
Writing:  ['0x10', '0xef', '0xbe', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0']
Writing:  ['0x10', '0x0', '0xa', '0x10', '0x41', '0x54', '0x2b', '0x46', '0x41', '0x43', '0x54', '0x4f', '0x52', '0x59', '0x52', '0x45', '0x53', '0x45', '0x54', '0xa']
ERROR: Timed out waiting for a response.
Traceback (most recent call last):
  File "code.py", line 23, in <module>
  File "adafruit_bluefruitspi.py", line 338, in command_check_OK
  File "adafruit_bluefruitspi.py", line 333, in command
RuntimeError: AT command failure: RuntimeError('Timed out waiting for a response.',)
```

**Comment by FoamyGuy** [comment]
I'm not certain, but I think this library is not for use with that device. My understanding is that this library is meant for connected to an ESP32 (note no S anything, just the standard ESP32) via a SPI connection from the microcontroller. 

If ESP32-S3 has bluetooth built-in to the main chip this library would not be the way to interact with it since it's not connected via SPI.

**Comment by dhalbert** [comment]
@FoamyGuy is correct; the library is for a coprocessor doing BLE.

**Comment by besupernow** [comment]
Okay thank you, so then would I use the regular adafruit_ble library for it? I have tried it but whenever I attempt to import services.nordic, it gives a NotImplementedError exception

**Comment by dhalbert** [comment]
The ESP32-S3 BLE implementation is not finished, hence the error you see. We just started on S3 implementations. In addition, the underlying software library we use is still very young and is buggy. The most complete BLE implementation is on the nRF boards. The ESP32 AirLift co-processor implementation does only BLE peripheral.

**Comment by besupernow** [comment]
Okay, I see, So I will have to wait for the S3 implementation to be finished before I am able to program my device? Thank you so much for helping me today!

**Comment by dhalbert** [comment]
Yes, it's really early, sorry.
